version: '3.9'
services:
  unconnect_wa:
    container_name: 
      unconnect_wa
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend-network
    ports:
      - "3005:3000"
    command: ["npm", "start"]
    environment:
      API_GATEWAY_URL: http://unconnect_ag:8000
networks:
  backend-network:
    driver: bridge
